# Generated by Django 3.1.5 on 2021-08-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='uploads/profile_pictures/profile_default.jpg', null=True, upload_to='uploads/profile_pictures'),
        ),
    ]
