# Generated by Django 3.2.6 on 2021-10-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_basic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Python Control Flow tools', max_length=20)),
                ('if_Statements', models.TextField(blank=True, null=True)),
                ('for_Statements', models.TextField(blank=True, null=True)),
                ('range_Function', models.TextField(blank=True, null=True)),
                ('break_and_continue_Statements', models.TextField(blank=True, null=True)),
                ('pass_Statements', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='basic',
            name='title',
            field=models.CharField(default='Basics of Python', max_length=20),
        ),
    ]
